// Objective-C API for talking to github.com/tendermint/basecoin/modules/coin/bindings Go package.
//   gobind -lang=objc github.com/tendermint/basecoin/modules/coin/bindings
//
// File is generated by gobind. Do not edit.

#ifndef __Bindings_H__
#define __Bindings_H__

@import Foundation;
#include "Universe.objc.h"


@class BindingsAccountResult;
@class BindingsClient;
@class BindingsMyCoin;

@interface BindingsAccountResult : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (long)height;
- (void)setHeight:(long)v;
- (NSString*)key;
- (void)setKey:(NSString*)v;
- (NSString*)error;
- (void)setError:(NSString*)v;
- (BindingsMyCoin*)myCoin:(long)i;
- (long)numCoins;
@end

@interface BindingsClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (NSString*)directoryPath;
- (void)setDirectoryPath:(NSString*)v;
- (void)init_;
@end

@interface BindingsMyCoin : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (id)initWithRef:(id)ref;
- (NSString*)denom;
- (void)setDenom:(NSString*)v;
- (long)amount;
- (void)setAmount:(long)v;
@end

FOUNDATION_EXPORT BindingsAccountResult* BindingsGetAccount(NSString* hexAddr, NSString* url);

FOUNDATION_EXPORT BindingsMyCoin* BindingsGetCoin();

FOUNDATION_EXPORT BindingsClient* BindingsNewClient();

#endif
